"""Drops redundant indexes

Revision ID: 000000000022
Revises: 000000000021
Create Date: 2024-10-08 14:10:34.174702

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "000000000022"
down_revision = "000000000021"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_api_key_id", table_name="api_key")
    op.drop_index("ix_node_benchmark_id", table_name="node_benchmark")
    op.drop_index("ix_node_info_id", table_name="node_info")
    op.drop_index("ix_node_metrics_id", table_name="node_metrics")
    op.drop_index("ix_usage_tokens_id", table_name="usage_tokens")
    op.drop_index("ix_user_profile_id", table_name="user_profile")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_profile_id", "user_profile", ["id"], unique=False)
    op.create_index("ix_usage_tokens_id", "usage_tokens", ["id"], unique=False)
    op.create_index("ix_node_metrics_id", "node_metrics", ["id"], unique=False)
    op.create_index("ix_node_info_id", "node_info", ["id"], unique=False)
    op.create_index("ix_node_benchmark_id", "node_benchmark", ["id"], unique=False)
    op.create_index("ix_api_key_id", "api_key", ["id"], unique=False)
    # ### end Alembic commands ###
