"""Adds node_health table

Revision ID: 000000000030
Revises: 000000000029
Create Date: 2024-10-23 10:46:14.701285

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000030"
down_revision = "000000000029"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_health",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_info_id", sa.UUID(), nullable=False),
        sa.Column("cpu_percent", sa.Integer(), nullable=False),
        sa.Column("ram_percent", sa.Integer(), nullable=False),
        sa.Column("disk_percent", sa.Integer(), nullable=False),
        sa.Column(
            "gpu_percent", sa.ARRAY(sa.Integer()), nullable=False, server_default="{}"
        ),
        sa.Column(
            "vram_percent", sa.ARRAY(sa.Integer()), nullable=False, server_default="{}"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_info_id"],
            ["node_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("node_health")
    # ### end Alembic commands ###
