"""Add agent_attestation table

Revision ID: 000000000062
Revises: 000000000061
Create Date: 2025-03-11 13:42:34.739393

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '000000000062'
down_revision = '000000000061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        'agent_attestation',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agent_instance_id', sa.UUID(), nullable=False),
        sa.Column('attestation', sa.String(), nullable=False),
        sa.Column('valid_from', sa.DateTime(), nullable=False),
        sa.Column('valid_to', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instance.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_instance', sa.Column('pcr0', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('agent_instance', 'pcr0')
    op.drop_table('agent_attestation')
    # ### end Alembic commands ###
