"""Rename Unlimited usage tier to Infinite

Revision ID: 000000000034
Revises: 000000000033
Create Date: 2024-10-28 11:03:17.697778

"""

from alembic import op

from database import PAID_TIER_UUID

# revision identifiers, used by Alembic.
revision = "000000000034"
down_revision = "000000000033"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""
        UPDATE usage_tier 
        SET name = 'Infinite'
        WHERE id = '{PAID_TIER_UUID}';
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
