"""Add agents table metadata JSON column

Revision ID: 000000000063
Revises: 000000000062
Create Date: 2025-03-13 08:15:29.088067

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "000000000063"
down_revision = "000000000062"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column(
        "agents",
        sa.Column(
            "agent_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("agents", "agent_metadata")
    # ### end Alembic commands ###
