"""Adds node metrics and info

Revision ID: 000000000004
Revises: 000000000003
Create Date: 2024-08-29 14:09:51.323897

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000004"
down_revision = "000000000003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_info",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_profile_id", sa.UUID(), nullable=False),
        sa.Column("gpu_model", sa.String(), nullable=True),
        sa.Column("vram", sa.Integer(), nullable=True),
        sa.Column("cpu_model", sa.String(), nullable=True),
        sa.Column("ram", sa.Integer(), nullable=True),
        sa.Column("network_speed", sa.Float(), nullable=True),
        sa.Column("operating_system", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_profile_id"],
            ["user_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_profile_id"),
    )
    op.create_index(op.f("ix_node_info_id"), "node_info", ["id"], unique=False)
    op.create_table(
        "node_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_profile_id", sa.UUID(), nullable=False),
        sa.Column("requests_served", sa.Integer(), nullable=True),
        sa.Column("time_to_first_token", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_profile_id"],
            ["user_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_profile_id"),
    )
    op.create_index(op.f("ix_node_metrics_id"), "node_metrics", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_node_metrics_id"), table_name="node_metrics")
    op.drop_table("node_metrics")
    op.drop_index(op.f("ix_node_info_id"), table_name="node_info")
    op.drop_table("node_info")
    # ### end Alembic commands ###
