"""Add user_profile table terms_of_service_agreement_at optional datetime column

Revision ID: 000000000042
Revises: 000000000041
Create Date: 2024-11-26 15:05:31.972289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000042'
down_revision = '000000000041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('terms_of_service_agreement_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'terms_of_service_agreement_at')
    # ### end Alembic commands ###
