"""Add power_limit to node_info

Revision ID: 000000000042
Revises: 000000000041
Create Date: 2024-11-21 12:38:08.859085

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000042"
down_revision = "000000000041"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("node_info", sa.Column("power_limit", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_info", "power_limit")
    # ### end Alembic commands ###
