"""Verified completions

Revision ID: 000000000047
Revises: 000000000046
Create Date: 2024-12-19 08:56:26.680062

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "000000000047"
down_revision = "000000000046"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verified_completions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("request", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("response", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.Column("signature", sa.String(), nullable=False),
        sa.Column("attestation", sa.String(), nullable=False),
        sa.Column("tx_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verified_completions_api_key"),
        "verified_completions",
        ["api_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verified_completions_hash"),
        "verified_completions",
        ["hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_verified_completions_hash"), table_name="verified_completions"
    )
    op.drop_index(
        op.f("ix_verified_completions_api_key"), table_name="verified_completions"
    )
    op.drop_table("verified_completions")
    # ### end Alembic commands ###
