"""Adds status Enum for NodeMetrics table

Revision ID: 000000000036
Revises: 000000000035
Create Date: 2024-10-29 14:58:33.113595

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000037"
down_revision = "000000000036"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        "CREATE TYPE nodestatus AS ENUM ('RUNNING', 'RUNNING_BENCHMARKING', 'RUNNING_DEGRADED', 'STOPPED', 'STOPPED_BENCHMARK_FAILED', 'STOPPED_DEGRADED')"
    )
    op.add_column(
        "node_metrics",
        sa.Column(

            "status",
            sa.Enum(
                "RUNNING",
                "RUNNING_BENCHMARKING",
                "RUNNING_DEGRADED",
                "STOPPED",
                "STOPPED_BENCHMARK_FAILED",
                "STOPPED_DEGRADED",
                name="nodestatus",
            ),
            nullable=True,
        ),
    )
    op.execute("UPDATE node_metrics SET status='STOPPED';")
    op.alter_column("node_metrics", "status", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_metrics", "status")
    op.execute("DROP TYPE nodestatus")
    # ### end Alembic commands ###
