"""Adds agent instance env vars

Revision ID: 000000000056
Revises: 000000000055
Create Date: 2025-02-20 13:24:35.222019

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "000000000056"
down_revision = "000000000055"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_instance",
        sa.Column(
            "instance_env_vars", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    op.alter_column(
        "agent_version", "docker_image_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent_version", "docker_image_hash", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("agent_instance", "instance_env_vars")
    # ### end Alembic commands ###
