"""Adds created_at and updated_at to UsageTokens table

Revision ID: 000000000004
Revises: 000000000003
Create Date: 2024-08-29 12:15:22.700088

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000004"
down_revision = "000000000003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usage_tokens", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "usage_tokens", sa.Column("last_updated_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_tokens", "last_updated_at")
    op.drop_column("usage_tokens", "created_at")
    # ### end Alembic commands ###
