"""Adds more metrics

Revision ID: 000000000009
Revises: 000000000008
Create Date: 2024-09-05 11:34:44.733950

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000009"
down_revision = "000000000008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_metrics",
        sa.Column(
            "requests_successful", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "node_metrics",
        sa.Column("requests_failed", sa.Integer(), server_default="0", nullable=False),
    )
    # set requests_served to 0 where it's NULL
    op.execute(
        "UPDATE node_metrics SET requests_served = 0 WHERE requests_served IS NULL"
    )
    op.alter_column(
        "node_metrics", "requests_served", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "node_metrics", "requests_served", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("node_metrics", "requests_failed")
    op.drop_column("node_metrics", "requests_successful")
    # ### end Alembic commands ###
