"""Add inference tokens per second in node metrics

Revision ID: 000000000025
Revises: 000000000024
Create Date: 2024-10-14 11:02:41.808322

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000025"
down_revision = "000000000024"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_metrics",
        sa.Column("inference_tokens_per_second", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_metrics", "inference_tokens_per_second")
    # ### end Alembic commands ###
