"""Adds model_name to NodeMetrics together with connected_at

Revision ID: 000000000026
Revises: 000000000025
Create Date: 2024-10-15 09:58:23.160936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000026'
down_revision = '000000000025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_metrics', sa.Column('model_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_metrics', 'model_name')
    # ### end Alembic commands ###
