"""Adds healthy flag to node_metrics

Revision ID: 000000000027
Revises: 000000000026
Create Date: 2024-10-14 10:19:54.684429

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000027"
down_revision = "000000000026"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_metrics",
        sa.Column("is_healthy", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_metrics", "is_healthy")
    # ### end Alembic commands ###
