"""Add connection timestamp

Revision ID: 000000000021
Revises: 000000000020
Create Date: 2024-10-07 19:17:05.808216

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000021"
down_revision = "000000000020"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_metrics", sa.Column("connected_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_metrics", "connected_at")
    # ### end Alembic commands ###
