"""user_profile table add is_password column to understand if a user has gone through the registration flow

Revision ID: 000000000011
Revises: 000000000010
Create Date: 2024-09-10 15:54:46.604788

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000011"
down_revision = "000000000010"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile", sa.Column("is_password_set", sa.Boolean(), nullable=True)
    )
    op.execute(
        "UPDATE user_profile SET is_password_set = false WHERE is_password_set IS NULL"
    )
    op.alter_column(
        "user_profile", "is_password_set", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "is_password_set")
    # ### end Alembic commands ###
