"""Puts NodeMetrics under NodeInfo

Revision ID: 000000000012
Revises: 000000000011
Create Date: 2024-09-12 16:56:30.014432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000012'
down_revision = '000000000011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('node_info_user_profile_id_key', 'node_info', type_='unique')
    # Adding new column node_info_id
    op.add_column('node_metrics', sa.Column('node_info_id', sa.UUID(), nullable=True))
    # set values for node_info_id
    op.execute("""
    UPDATE node_metrics
    SET node_info_id = (
        SELECT node_info.id
        FROM node_info
        WHERE node_info.user_profile_id = node_metrics.user_profile_id
    )
    WHERE EXISTS (
        SELECT 1
        FROM node_info
        WHERE node_info.user_profile_id = node_metrics.user_profile_id
    );
    """)
    op.drop_constraint('node_metrics_user_profile_id_key', 'node_metrics', type_='unique')
    op.create_unique_constraint(None, 'node_metrics', ['node_info_id'])
    op.drop_constraint('node_metrics_user_profile_id_fkey', 'node_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'node_metrics', 'node_info', ['node_info_id'], ['id'])
    op.drop_column('node_metrics', 'user_profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_metrics', sa.Column('user_profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'node_metrics', type_='foreignkey')
    op.create_foreign_key('node_metrics_user_profile_id_fkey', 'node_metrics', 'user_profile', ['user_profile_id'], ['id'])
    op.drop_constraint(None, 'node_metrics', type_='unique')
    op.create_unique_constraint('node_metrics_user_profile_id_key', 'node_metrics', ['user_profile_id'])
    op.drop_column('node_metrics', 'node_info_id')
    op.create_unique_constraint('node_info_user_profile_id_key', 'node_info', ['user_profile_id'])
    # ### end Alembic commands ###
