"""Add user_credits_addition table to showcase credits additions

Revision ID: 000000000036
Revises: 000000000035
Create Date: 2024-10-29 11:16:15.989841

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "000000000036"
down_revision = "000000000035"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_credits_addition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_credits_id", sa.UUID(), nullable=False),
        sa.Column("credits_change", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_credits_id"],
            ["user_credits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_credits_addition")
    # ### end Alembic commands ###
