"""add node_id unique constraint to node benchmark

Revision ID: 000000000038
Revises: 000000000037
Create Date: 2024-11-13 10:02:32.719686

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "000000000038"
down_revision = "000000000037"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_node_model", "node_benchmark", type_="unique")
    op.create_unique_constraint("uq_node_id", "node_benchmark", ["node_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_node_model", "node_benchmark", ["node_id", "model_name"]
    )
    op.drop_constraint("uq_node_id", "node_benchmark", type_="unique")
    # ### end Alembic commands ###
