"""Adds username and profile_data

Revision ID: 000000000016
Revises: 000000000015
Create Date: 2024-09-17 11:26:14.558641

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "000000000016"
down_revision = "000000000015"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_profile", sa.Column("username", sa.String(), nullable=True))
    op.add_column(
        "user_profile", sa.Column("profile_data", postgresql.JSON(), nullable=True)
    )
    op.create_unique_constraint(None, "user_profile", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_profile_username_key", "user_profile", type_="unique")
    op.drop_column("user_profile", "profile_data")
    op.drop_column("user_profile", "username")
    # ### end Alembic commands ###
