"""Sets everything under NodeInfo to be nullable

Revision ID: 000000000013
Revises: 000000000012
Create Date: 2024-09-13 10:58:19.634289

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000013"
down_revision = "000000000012"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("node_info", "cpu_model", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("node_info", "cpu_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("node_info", "ram", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "node_info", "operating_system", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "node_metrics", "node_info_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "node_metrics", "node_info_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "node_info", "operating_system", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("node_info", "ram", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "node_info", "cpu_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "node_info", "cpu_model", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
