"""Remove node_metrics table is_healthy column, in favor of status column

Revision ID: 000000000040
Revises: 000000000039
Create Date: 2024-11-20 13:14:52.167503

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000040"
down_revision = "000000000039"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_metrics", "is_healthy")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_metrics",
        sa.Column(
            "is_healthy", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
    )
    # set requests_served to 0 where it's NULL
    op.execute("UPDATE node_metrics SET is_healthy = true WHERE is_healthy IS NULL")
    op.alter_column(
        "node_metrics", "is_healthy", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
