"""Adds tee_host_base_url to agent_instance

Revision ID: 000000000060
Revises: 000000000059
Create Date: 2025-03-06 14:44:54.593374

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000060"
down_revision = "000000000059"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_instance", sa.Column("tee_host_base_url", sa.String(), nullable=True)
    )
    op.execute(
        "UPDATE agent_instance SET tee_host_base_url = 'http://52.57.178.129:5000/'"
    )
    op.alter_column("agent_instance", "tee_host_base_url", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_instance", "tee_host_base_url")
    # ### end Alembic commands ###
