"""Add nemo model limits

Revision ID: 000000000041
Revises: 000000000040
Create Date: 2024-11-26 13:21:44.530517

"""

from alembic import op
import sqlalchemy as sa

from database import FREE_TIER_UUID
from database import PAID_TIER_UUID

# revision identifiers, used by Alembic.
revision = "000000000041"
down_revision = "000000000040"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""
    INSERT INTO usage_limit (
        id,
        usage_tier_id,
        model_name,
        max_tokens_per_minute,
        max_tokens_per_day,
        max_requests_per_minute,
        max_requests_per_day,
        created_at,
        last_updated_at
    ) VALUES (
        '06745b26-85b0-7ac3-8000-7bcfbff36d04',
        '{FREE_TIER_UUID}',
        'neuralmagic/Mistral-Nemo-Instruct-2407-quantized.w4a16',
        20000,
        2000000,
        20,
        11000,
        now(),
        now()
    );
    """
    )
    op.execute(
        f"""
    INSERT INTO usage_limit (
        id,
        usage_tier_id,
        model_name,
        max_tokens_per_minute,
        max_tokens_per_day,
        max_requests_per_minute,
        max_requests_per_day,
        price_per_million_tokens,
        created_at,
        last_updated_at
    ) VALUES (
        '06745b27-1544-7d01-8000-b344bd2e67d6',
        '{PAID_TIER_UUID}',
        'neuralmagic/Mistral-Nemo-Instruct-2407-quantized.w4a16',
        NULL,
        NULL,
        NULL,
        NULL,
        0.11,
        now(),
        now()
    );
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""
    DELETE FROM usage_limit 
    WHERE model_name = 'neuralmagic/Mistral-Nemo-Instruct-2407-quantized.w4a16';
    """
    )
    # ### end Alembic commands ###
