"""Add power_percent to node health

Revision ID: 000000000042
Revises: 000000000041
Create Date: 2024-11-21 13:29:11.196013

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000042"
down_revision = "000000000041"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_health",
        sa.Column("power_percent", sa.ARRAY(sa.Integer()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_health", "power_percent")
    # ### end Alembic commands ###
