"""Adds gpu_count to node info

Revision ID: 000000000029
Revises: 000000000028
Create Date: 2024-10-17 11:28:49.823874

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000029"
down_revision = "000000000028"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_info",
        sa.Column("gpu_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_info", "gpu_count")
    # ### end Alembic commands ###
