"""Add active flag and node version

Revision ID: 000000000019
Revises: 000000000018
Create Date: 2024-09-27 17:24:01.841288

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000019"
down_revision = "000000000018"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_info",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column("node_info", sa.Column("version", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_info", "version")
    op.drop_column("node_info", "is_active")
    # ### end Alembic commands ###
