"""node_info table split network_speed to network_download_speed and network_upload_speed, add cpu_count column

Revision ID: 000000000006
Revises: 000000000005
Create Date: 2024-08-30 11:24:18.909697

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000006"
down_revision = "000000000005"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("node_info", sa.Column("cpu_count", sa.Integer(), nullable=False))
    op.add_column(
        "node_info", sa.Column("network_download_speed", sa.Float(), nullable=True)
    )
    op.add_column(
        "node_info", sa.Column("network_upload_speed", sa.Float(), nullable=True)
    )
    op.drop_column("node_info", "network_speed")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_info",
        sa.Column(
            "network_speed",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("node_info", "network_upload_speed")
    op.drop_column("node_info", "network_download_speed")
    op.drop_column("node_info", "cpu_count")
    # ### end Alembic commands ###
