"""Makes RTT nullable

Revision ID: 000000000027
Revises: 000000000026
Create Date: 2024-10-16 12:12:41.085704

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000027"
down_revision = "000000000026"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "node_metrics",
        "rtt",
        existing_type=sa.INTEGER(),
        nullable=True,
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "node_metrics",
        "rtt",
        existing_type=sa.INTEGER(),
        nullable=False,
        server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
