"""Adds usage tiers

Revision ID: 000000000024
Revises: 000000000023
Create Date: 2024-10-09 13:10:55.643404

"""

import datetime

from alembic import op
import sqlalchemy as sa

from database import FREE_TIER_UUID

# revision identifiers, used by Alembic.
revision = "000000000024"
down_revision = "000000000023"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_tier",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("max_tokens_per_minute", sa.Integer(), nullable=True),
        sa.Column("max_tokens_per_day", sa.Integer(), nullable=True),
        sa.Column("max_requests_per_minute", sa.Integer(), nullable=True),
        sa.Column("max_requests_per_day", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.execute(
        f"""
        INSERT INTO usage_tier (id, name, description, max_tokens_per_minute, max_tokens_per_day, max_requests_per_minute, max_requests_per_day, created_at, last_updated_at)
        VALUES ('{FREE_TIER_UUID}', 'Free Tier', 'Default free usage tier', 40000, 1000000, 60, 28800, '{datetime.datetime.now(datetime.UTC)}', '{datetime.datetime.now(datetime.UTC)}');
        """
    )
    op.add_column(
        "user_profile",
        sa.Column(
            "usage_tier_id",
            sa.UUID(),
            server_default=FREE_TIER_UUID,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "user_profile_usage_tier_id_fkey",
        "user_profile",
        "usage_tier",
        ["usage_tier_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_profile_usage_tier_id_fkey", "user_profile", type_="foreignkey"
    )
    op.drop_column("user_profile", "usage_tier_id")
    op.drop_table("usage_tier")
    # ### end Alembic commands ###
