"""Adds agent_instance_id to agent_logs

Revision ID: 000000000059
Revises: 000000000058
Create Date: 2025-03-06 10:14:39.450847

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000059"
down_revision = "000000000058"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_logs", sa.Column("agent_instance_id", sa.UUID(), nullable=True)
    )

    # Update existing agent_logs with agent_instance_id from agent_instance table
    # Assuming agent_logs has agent_id that can be used to join with agent_instance
    op.execute(
        """
        UPDATE agent_logs
        SET agent_instance_id = (
            SELECT id FROM agent_instance 
            WHERE agent_instance.agent_id = agent_logs.agent_id AND agent_instance.is_deleted = false
            LIMIT 1
        )
    """
    )

    # Make the column non-nullable after populating data
    op.alter_column("agent_logs", "agent_instance_id", nullable=False)

    op.create_foreign_key(
        None, "agent_logs", "agent_instance", ["agent_instance_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "agent_logs", type_="foreignkey")
    op.drop_column("agent_logs", "agent_instance_id")
    # ### end Alembic commands ###
