"""Remove user id in solana_faucet_request table

Revision ID: 000000000058
Revises: 000000000057
Create Date: 2025-03-04 13:34:14.712137

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000058"
down_revision = "000000000057"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_faucet_user_time", table_name="faucet_request")
    op.drop_constraint(
        "faucet_request_user_profile_id_fkey", "faucet_request", type_="foreignkey"
    )
    op.drop_column("faucet_request", "user_profile_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "faucet_request",
        sa.Column("user_profile_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "faucet_request_user_profile_id_fkey",
        "faucet_request",
        "user_profile",
        ["user_profile_id"],
        ["id"],
    )
    op.create_index(
        "idx_faucet_user_time",
        "faucet_request",
        ["user_profile_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
