"""Add DISABLED nodestatus enum values

Revision ID: 000000000039
Revises: 000000000038
Create Date: 2024-11-20 11:48:30.382687

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "000000000039"
down_revision = "000000000038"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.execute("ALTER TYPE nodestatus ADD VALUE 'RUNNING_DISABLED';")
    op.execute("ALTER TYPE nodestatus ADD VALUE 'STOPPED_DISABLED';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
