"""adds user_model_usage_24h table for tracking daily user and model usage

Revision ID: 000000000042
Revises: 000000000041
Create Date: 2024-11-27 13:56:28.218475

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000042"
down_revision = "000000000041"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model_usage_24h",
        sa.Column("consumer_user_profile_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column(
            "usage_date", sa.Date(), nullable=False, server_default=sa.text("NOW()")
        ),
        sa.Column("tokens_consumed", sa.BigInteger(), nullable=False),
        sa.Column("requests_count", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("consumer_user_profile_id", "model_name", "usage_date"),
    )
    op.alter_column(
        "node_info",
        "gpu_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_model_usage_24h")
    # ### end Alembic commands ###
