"""Adds uptime to node metrics

Revision ID: 000000000007
Revises: 000000000006
Create Date: 2024-08-30 11:22:43.902595

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000007"
down_revision = "000000000006"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_metrics",
        sa.Column("uptime", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_metrics", "uptime")
    # ### end Alembic commands ###
