"""Add is_archived column to node_info table

Revision ID: 000000000035
Revises: 000000000034
Create Date: 2024-10-28 14:17:49.800784

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000035"
down_revision = "000000000034"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("node_info", sa.Column("is_archived", sa.Boolean(), nullable=True))
    op.execute("UPDATE node_info SET is_archived = False WHERE is_archived IS NULL")
    op.alter_column(
        "node_info", "is_archived", existing_type=sa.Boolean(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_info", "is_archived")
    # ### end Alembic commands ###
