"""Added rtt to metrics

Revision ID: 000000000020
Revises: 000000000019
Create Date: 2024-10-07 14:11:40.452858

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "000000000020"
down_revision = "000000000019"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node_metrics",
        sa.Column("rtt", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node_metrics", "rtt")
    # ### end Alembic commands ###
