"""Makes hash in verified_completions unique

Revision ID: 000000000053
Revises: 000000000052
Create Date: 2025-01-20 12:46:40.221974

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "000000000053"
down_revision = "000000000052"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verified_completions_hash", table_name="verified_completions")
    op.create_index(
        op.f("ix_verified_completions_hash"),
        "verified_completions",
        ["hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_verified_completions_hash"), table_name="verified_completions"
    )
    op.create_index(
        "ix_verified_completions_hash", "verified_completions", ["hash"], unique=False
    )
    # ### end Alembic commands ###
