"""Makes tx_hash a nullable field in verified_completions table

Revision ID: 000000000052
Revises: 000000000051
Create Date: 2025-01-20 11:46:40.323178

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000052"
down_revision = "000000000051"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verified_completions", "tx_hash", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verified_completions", "tx_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
