"""user_profile table add optional authentication_id column to handle logging in

Revision ID: 000000000010
Revises: 000000000009
Create Date: 2024-09-10 15:44:00.227609

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000010"
down_revision = "000000000009"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile", sa.Column("authentication_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "authentication_id")
    # ### end Alembic commands ###
