"""Add signature string column to agent_logs table

Revision ID: 000000000061
Revises: 000000000060
Create Date: 2025-03-10 10:00:21.668689

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "000000000061"
down_revision = "000000000060"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("agent_logs", sa.Column("signature", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("agent_logs", "signature")
    # ### end Alembic commands ###
