"""Adds verified completions limits

Revision ID: 000000000048
Revises: 000000000047
Create Date: 2024-12-20 13:04:22.421746

"""

from alembic import op
import sqlalchemy as sa

from database import FREE_TIER_UUID
from database import PAID_TIER_UUID

# revision identifiers, used by Alembic.
revision = "000000000048"
down_revision = "000000000047"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""
    INSERT INTO usage_limit (
        id,
        usage_tier_id,
        model_name,
        max_tokens_per_minute,
        max_tokens_per_day,
        max_requests_per_minute,
        max_requests_per_day,
        created_at,
        last_updated_at
    ) VALUES (
        '06745b27-1544-7d01-8000-b344bd2e67d7',
        '{FREE_TIER_UUID}',
        'verified_completions',
        40000,
        4000000,
        60,
        33000,
        now(),
        now()
    );
    """
    )
    op.execute(
        f"""
    INSERT INTO usage_limit (
        id,
        usage_tier_id,
        model_name,
        max_tokens_per_minute,
        max_tokens_per_day,
        max_requests_per_minute,
        max_requests_per_day,
        created_at,
        last_updated_at
    ) VALUES (
        '06745b27-1544-7d01-8000-b344bd2e67d8',
        '{PAID_TIER_UUID}',
        'verified_completions',
        40000,
        4000000,
        60,
        33000,
        now(),
        now()
    );
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""
    DELETE FROM usage_limit 
    WHERE model_name = 'verified_completions';
    """
    )
    # ### end Alembic commands ###
