"""Adds agent versioning

Revision ID: 000000000055
Revises: 000000000054
Create Date: 2025-02-14 11:54:25.682283

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "000000000055"
down_revision = "000000000054"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("docker_image", sa.String(), nullable=False),
        sa.Column("docker_image_hash", sa.String(), nullable=True),
        sa.Column("env_vars", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("agents", sa.Column("docker_image_hash", sa.String(), nullable=True))
    op.execute("UPDATE agents SET docker_image_hash = 'unknown' WHERE docker_image_hash IS NULL")
    op.alter_column(
        "agents", "docker_image_hash", existing_type=sa.String(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "docker_image_hash")
    op.drop_table("agent_version")
    # ### end Alembic commands ###
