"""Add level column to agent_logs table

Revision ID: 000000000054
Revises: 000000000053
Create Date: 2025-01-27 15:55:26.721180

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "000000000054"
down_revision = "000000000053"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("agent_logs", sa.Column("level", sa.String(), nullable=True))

    op.execute("UPDATE agent_logs SET level = 'thought' WHERE level IS NULL")

    op.alter_column(
        "agent_logs",
        "level",
        existing_type=sa.String(),
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("agent_logs", "level")
    # ### end Alembic commands ###
