version: "3"
services:
  db:
    env_file:
      - .env
    image: "postgres:16.4"
    container_name: "inference_db_postgres"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata-inference-postgres:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  dbdata-inference-postgres:

networks:
  shared_network:
    external: true
