name: Lint MyPy, Pyright & Pylint

on:
  pull_request:

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    outputs:
      mypy_errors: ${{ steps.mypy-count.outputs.error_count }}
      pyright_errors: ${{ steps.pyright-count.outputs.error_count }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
          pip install mypy pyright
      - name: Run PyLint
        run: pylint --rcfile=setup.cfg distributedinference/*

      - name: Create output directory
        run: mkdir -p mypy_pyright_outputs
      - name: Run mypy and save output
        run: |
          mypy distributedinference/ > mypy_pyright_outputs/mypy_output.txt || true
        continue-on-error: true
      - name: Count mypy errors
        id: mypy-count
        run: |
          error_count=$(grep -c "error:" mypy_output.txt || true)
          echo "mypy error count: $error_count"
          echo "::set-output name=error_count::$error_count"
      - name: Print mypy output
        run: |
          echo "=== mypy output ==="
          cat mypy_pyright_outputs/mypy_output.txt
      - name: Run pyright and save output
        run: |
          pyright distributedinference/ > mypy_pyright_outputs/pyright_output.txt || true
        continue-on-error: true
      - name: Count pyright errors
        id: pyright-count
        run: |
          error_count=$(grep -c "error" pyright_output.txt || true)
          echo "pyright error count: $error_count"
          echo "::set-output name=error_count::$error_count"
      - name: Print pyright output
        run: |
          echo "=== pyright output ==="
          cat mypy_pyright_outputs/pyright_output.txt
      - name: Upload mypy and pyright outputs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mypy-pyright-outputs
          path: mypy_pyright_outputs/
  lint-summary:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    if: success()
    steps:
      - name: Display Linting Summary
        run: |
          mypy_errors="${{ needs.lint-and-type-check.outputs.mypy_errors }}"
          pyright_errors="${{ needs.lint-and-type-check.outputs.pyright_errors }}"
          echo "Linting completed. Found $mypy_errors mypy errors and $pyright_errors pyright errors."
          
          # Set custom status for the check-run (if needed)
          if [[ "$mypy_errors" -gt 0 || "$pyright_errors" -gt 0 ]]; then
            echo "::warning ::Linting issues found: $mypy_errors mypy errors, $pyright_errors pyright errors"
          else
            echo "::notice ::No linting issues detected."
          fi
  
