name: Lint MyPy, Pyright & Pylint

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
          pip install mypy pyright
      - name: Run PyLint
        run: pylint --rcfile=setup.cfg distributedinference/*

      - name: Run mypy and save output
        run: |
          mypy distributedinference/ > mypy_output.txt || true
        continue-on-error: true
      - name: Print mypy output
        run: |
          echo "=== mypy output ==="
          cat mypy_output.txt
      - name: Run pyright and save output
        run: |
          pyright distributedinference/ > pyright_output.txt || true
        continue-on-error: true
      - name: Print pyright output
        run: |
          echo "=== pyright output ==="
          cat pyright_output.txt
      - name: Upload mypy output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: mypy-results
          path: mypy_output.txt
      - name: Upload pyright output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pyright-results
          path: pyright_output.txt
